modLoader="javafml" 
license="GNU LESSER GENERAL PUBLIC LICENSE" 
loaderVersion="[36,)" 
issueTrackerURL="https://github.com/HungTeen/pvzmod/issues"

[[mods]]
modId="pvz"
version="0.5.2"
displayName="Plants vs Zombies"
authors="_HungTeen_" 
displayURL="https://space.bilibili.com/362855464" 
logoFile="logo.png" 
credits="Model Helper : Wolf__Crystal, Men_Tian_Bai, InkyTheSheep, Chompy and so on." 
description='''
A mod that brings Plants vs Zombies to Minecraft'''

[[dependencies.pvz]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    
[[dependencies.pvz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"