modLoader="javafml" #mandatory

license="GNU LESSER GENERAL PUBLIC LICENSE" #mandatory

loaderVersion="[36,)" #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/HungTeen/pvzmod/issues" #optional

displayURL="https://space.bilibili.com/362855464" #optional

logoFile="logo.png" #optional

credits="Model Helper : Wolf__Crystal, Men_Tian_Bai, InkyTheSheep, Chompy and so on." #optional

authors="_HungTeen_" #optional

[[mods]]
modId="pvz"
version="0.5.1"
displayName="Plants vs Zombies"
description='''
A mod that brings Plants vs Zombies to Minecraft'''

[[dependencies.pvz]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"